services:
  - type: web
    name: ryan-xit-ultimate
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    healthCheckPath: ""
